// layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import BackButton from "@/components/ฺBackButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col h-auto">
        <Navbar />

        <main className="h-auto flex-1 bg-sky-50 dark:bg-zinc-900 p-4">
          <BackButton />
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
